version: "3.9"
services:
  web:
    build: .
    env_file:
      - .env
    # Override values in .env
    environment:
      - DATABASE_URL=file:/data/sqlite.db
      - PORT=${CONTAINER_PORT}
    ports:
      - "${CONTAINER_PORT}:${CONTAINER_PORT}"
    volumes:
      - data:/data

volumes:
  data: